name: ☂ run API tests

on:
  workflow_dispatch:

jobs:
   api-test:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
         node-version: '16'
      - name: install dependencies
        run: npm install
      - name: run tests
        run: npm run test:api
        continue-on-error: true
